dev: Development changes

diff --git a/.github/workflows/node-release.yaml b/.github/workflows/node-release.yaml
--- a/.github/workflows/node-release.yaml
+++ b/.github/workflows/node-release.yaml
@@ -25,86 +25,53 @@ on:
       DOCKERHUB_PASS:
 
 jobs:
-  # ***********************************
-  # Job: Build Packages
-  # ***********************************
-  build:
-    name: Build Packages
-    uses: panates/github-actions/.github/workflows/node-build.yaml@dev
-    with:
-      build_script:  ${{ inputs.build_script }}
-    secrets:
-      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-
-
-  # ***********************************
-  # Job: Publish npm packages
-  # ***********************************
-  npm_publish:
-    name: 'Publish npm packages'
-    needs:
-      - build
+  release:
+    name: "Release"
     runs-on: ubuntu-latest
-    steps:
-      - name: Download artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: 'artifacts'
-          path: './__artifacts__'
+    outputs:
+      lastTag: ${{ steps.environment.outputs.lastTag }}
 
-      - name: "Publish Npm Packages"
-        uses: panates/github-actions/.github/actions/node-release-npm@dev
+    steps:
+      - name: "Setup Environment"
+        uses: panates/gh-setup-node@v1
+        with:
+          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+          fetch-depth: 100
+
+      - name: "Scan Environment"
+        id: environment
+        uses: panates/gh-repository-info@v1
         with:
           token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
 
+      - name: "Check git tag"
+        run: |
+          if [ -z "${{ steps.environment.outputs.lastTag }}" ]; then
+            echo "Error: No git tag found."
+            exit 1
+          fi          
 
-#  # ***********************************
-#  # Job: Create GitHub release
-#  # ***********************************
-#  github_release:
-#    name: 'Create Github Release'
-#    needs:
-#      - build
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Download artifacts
-#        uses: actions/download-artifact@v4
-#        with:
-#          name: 'artifacts'
-#          path: './__artifacts__'
-#
-#      - name: "Create ZIP files"
-#        uses: panates/github-actions/.github/actions/github-release-artifacts@dev
-#
-#      - name: Create GitHub Release
-#        id: create_release
-#        uses: ncipollo/release-action@v1
-#        with:
-#          tag: ${{ needs.build.outputs.lastTag }}
-#          bodyFile: "__artifacts__/COMMIT_CHANGELOG.md"
-#          artifacts: "__release__/**/*"
-#          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
-#          draft: false
-#          prerelease: false
-#          replacesArtifacts: true
+      - name: "Build Changelog"
+        id: changelog
+        uses: panates/github-actions/.github/actions/node-build-changelog@dev
+        with:
+          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+          fromTag: ${{ steps.environment.outputs.prevSha }}
+          toTag: ${{ steps.environment.outputs.lastSha }}
 
-#  # ***********************************
-#  # Job: Create Docker Images
-#  # ***********************************
-#  dockerize:
-#    name: 'Create Docker Images'
-#    if: ${{ needs.publish_packages.outputs.appFiles != '' }}
-#    needs: publish_packages
-#    strategy:
-#      matrix:
-#        releaseFile: ${{ fromJson(needs.publish_packages.outputs.appFilesArray) }}
-#    uses: kimvar-inc/manifests/.github/workflows/docker-publish.yaml@main
-#    with:
-#      file_basename: ${{matrix.releaseFile}}
-#      image_prefix: "pntdockerhub/kimvar-"
-#      before_dockerize: ${{ inputs.before_dockerize }}
-#      stage_version: ${{ inputs.stage_version }}
-#    secrets:
-#      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-#      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
-#      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
+      - name: "Print changelog"
+        run: |
+          cat COMMIT_CHANGELOG.md
+
+      - name: "Build Packages"
+        shell: bash
+        run: |
+          ${{ inputs.build_script }}
+
+      - name: "Publish Packages"
+        uses: panates/github-actions/.github/actions/node-release@dev
+        with:
+          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+          packages: ${{ steps.environment.outputs.packages }}
+          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
+          dockerhub-password: ${{ secrets.DOCKERHUB_PASS }}
