dev: Development changes

diff --git a/.github/workflows/node-build.yaml b/.github/workflows/node-build.yaml
--- a/.github/workflows/node-build.yaml
+++ b/.github/workflows/node-build.yaml
@@ -31,6 +31,13 @@ jobs:
           token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
           fetch-depth: 100
 
+      - name: "Check git tag"
+        run: |
+          if [ -z "${{ steps.environment.outputs.lastTag }}" ]; then
+            echo "Error: No git tag found."
+            exit 1
+          fi          
+
       - name: "Scan Environment"
         id: environment
         uses: panates/gh-repository-info@v1
