dev: Development changes

diff --git a/.github/workflows/node-release.yaml b/.github/workflows/node-release.yaml
--- a/.github/workflows/node-release.yaml
+++ b/.github/workflows/node-release.yaml
@@ -68,59 +68,61 @@ jobs:
         with:
           token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
 
-#      - name: "Check git tag"
-#        run: |
-#          if [ -z "${{ steps.environment.outputs.lastTag }}" ]; then
-#            echo "Error: No git tag found."
-#            exit 1
-#          fi
-#
-#      - name: "Build Changelog"
-#        id: changelog
-#        uses: panates/github-actions/.github/actions/node-build-changelog@v1
-#        with:
-#          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-#          fromTag: ${{ steps.environment.outputs.prevSha }}
-#          toTag: ${{ steps.environment.outputs.lastSha }}
-#
-#      - name: "Print changelog"
-#        run: |
-#          cat COMMIT_CHANGELOG.md
-#
-#      - name: Create GitHub Release
-#        id: create_release
-#        uses: ncipollo/release-action@v1
-#        with:
-#          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-#          tag: ${{ steps.environment.outputs.lastTag }}
-#          bodyFile:  "COMMIT_CHANGELOG.md"
-#          draft: false
-#          prerelease: false
-#          replacesArtifacts: true
-#
-#      - name: "Build Packages"
-#        shell: bash
-#        run: |
-#          ${{ inputs.build_script }}
-#
-#      - name: "Publish Npm Packages"
-#        if: ${{ steps.environment.outputs.npmPackages && inputs.npm-publish == 'true'}}
-#        uses: panates/github-actions/.github/actions/release-npm@v1
-#        with:
-#          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-#          workspace: ${{ inputs.workspace }}
-#          packages: ${{ steps.environment.outputs.packages }}
-#
-#      - name: "Build Docker Images"
-#        if: ${{  steps.environment.outputs.dockerPackages && inputs.dockerize == 'true'}}
-#        uses: panates/github-actions/.github/actions/release-docker@v1
-#        with:
-#          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-#          workspace: ${{ inputs.workspace }}
-#          packages: ${{ steps.environment.outputs.packages }}
-#          platforms: ${{ inputs.docker-platforms }}
-#          docherhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
-#          docherhub-password: ${{ secrets.DOCKERHUB_PASS }}
+      - name: "Check git tag"
+        run: |
+          if [ -z "${{ steps.environment.outputs.lastTag }}" ]; then
+            echo "Error: No git tag found."
+            exit 1
+          fi
+
+      - name: "Build Changelog"
+        id: changelog
+        uses: panates/github-actions/.github/actions/node-build-changelog@v1
+        with:
+          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+          fromTag: ${{ steps.environment.outputs.prevSha }}
+          toTag: ${{ steps.environment.outputs.lastSha }}
+
+      - name: "Print changelog"
+        run: |
+          cat COMMIT_CHANGELOG.md
+
+      - name: Create GitHub Release
+        id: create_release
+        uses: ncipollo/release-action@v1
+        with:
+          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+          tag: ${{ steps.environment.outputs.lastTag }}
+          bodyFile:  "COMMIT_CHANGELOG.md"
+          draft: false
+          prerelease: false
+          replacesArtifacts: true
+
+      - name: "Build Packages"
+        shell: bash
+        run: |
+          ${{ inputs.build_script }}
+
+      - name: "Publish Npm Packages"
+        if: ${{ steps.environment.outputs.npmPackages && inputs.npm-publish == 'true'}}
+        uses: panates/github-actions/.github/actions/release-npm@v1
+        with:
+          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+          workspace: ${{ inputs.workspace }}
+          packages: ${{ steps.environment.outputs.packages }}
+
+      - name: "Build Docker Images"
+        if: ${{  steps.environment.outputs.dockerPackages && inputs.dockerize == 'true'}}
+        uses: panates/github-actions/.github/actions/release-docker@v1
+        with:
+          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+          workspace: ${{ inputs.workspace }}
+          packages: ${{ steps.environment.outputs.packages }}
+          platforms: ${{ inputs.docker-platforms }}
+          dockerhub-namespace: ${{ secrets.DOCKERHUB_NAMESPACE }}
+          docherhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
+          docherhub-password: ${{ secrets.DOCKERHUB_PASS }}
+          image-files: ${{ inputs.image-files }}
 
   stage_deploy:
     if: ${{ inputs.stage-repository != '' }}
@@ -136,14 +138,14 @@ jobs:
           ref: ${{ inputs.stage-repository-branch }}
 
       - name: Update image in deployment yaml
-        uses: panates/github-actions/.github/actions/stage-deploy@main
+        uses: panates/github-actions/.github/actions/stage-deploy@v1
         with:
           token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
           packages: ${{ needs.release.outputs.packages }}
           dockerhub-namespace: ${{ secrets.DOCKERHUB_NAMESPACE }}
           docherhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
           docherhub-password: ${{ secrets.DOCKERHUB_PASS }}
-          stage-files: ${{ inputs.stage-files }}
           image-files: ${{ inputs.image-files }}
+          stage-files: ${{ inputs.stage-files }}
 
 
